---
title: "Costruzione e validazione di strumenti di misura dell'efficacia dell'intervento psicologico in neuropsicologia"
date: "Pagina aggiornata il `r Sys.Date()`"
---

Questa è la pagina web dell'insegnamento *Costruzione e validazione di strumenti di misura dell'efficacia dell'intervento psicologico in neuropsicologia*, prof. [Corrado Caudek](https://ccaudek.github.io/caudeklab/), Corso di Laurea Magistrale in Psicologia Clinica e della Salute e Neuropsicologia (curriculum: assessment e intervento psicologico in neuropsicologia - E21), [Università degli Studi di Firenze](https://www.unifi.it), anno accademico 2022-2023.

_Questa pagina web verrà periodicamente aggiornata durante il periodo di svolgimento dell'insegnamento (marzo-maggio 2023)._

## Descrizione sintetica 

L'insegnamento *Costruzione e validazione di strumenti di misura dell'efficacia dell'intervento psicologico in neuropsicologia* ha lo scopo di fornire agli studenti le conoscenze di base di statistica, di analisi dei dati e di metodologia della ricerca che costituiscono uno degli aspetti centrali del bagaglio professionale dello psicologo. Il presente insegnamento non si limiterà ad una descrizione astratta degli argomenti trattati, anche perché tali concetti risultano poco comprensibili se non vengono utilizzati nell'ambito di applicazioni concrete. Gli argomenti del corso verranno invece accompagnati da esercitazioni pratiche e laboratori didattici. Per tali analisi guidate dei dati sarà necessario utilizzare un computer e un linguaggio di programmazione per l'analisi statistica dei dati. Poiché la psicometria e la statistica moderne possono essere eseguite utilizzando software open source, gli esempi saranno presentati in $\textsf{R}$. 

## Obiettivi formativi

- Conoscere il vocabolario e la logica fondamentali dell'assessment psicologico.
- Sviluppare la capacità di giudizio critico sull'adeguatezza delle misure atte a valutare il comportamento e le abilità cognitive.
- Conoscere parte della letteratura rilevante in materia di teoria e pratica psicometrica.

## Prerequisiti

Trattando di argomenti avanzati, questo insegnamento presuppone la conoscenza di base dei concetti fondamentali della teoria delle probabilità; presuppone inoltre il possesso delle conoscenze di base necessarie per procedere all'utilizzo di $\textsf{R}$. Informazioni su tali argomenti sono forniti nella dispensa di Psicometria (A.A. 2022-2023).

## Ulteriori informazioni

### Ricevimento

Questo è un periodo storico insolito, per tutti noi. Il COVID-19 non è ancora stato neutralizzato. Detto questo, e date le preoccupazioni per il mio benessere e il benessere dei membri della mia famiglia, durante le lezioni in presenza mi comporterò nel modo seguente: me ne andrò dall’aula immediatamente dopo avere finito la lezione. È normale voler chiedere al professore qualcosa in privato dopo la lezione, o anche solo chiacchierare con lui sugli argomenti della lezione, durante la pausa. Tuttavia, questo non è un momento normale e dobbiamo adattarci alla situazione in cui ci troviamo. Ciò nonostante, continuerò ad essere facilmente reperibile. Vi prego di _non_ inviarmi email. Vi incoraggio, invece, a contattarmi via Moodle, anche per organizzare incontri di gruppo (ma non necessariamente). In tali incontri potremo chiacchierare tranquillamente via Google Meet o Webex.

### Norme relative all'uso della posta elettronica

Di solito rispondo rapidamente alle e-mail degli studenti. Tuttavia, ricevo molto spesso richieste di informazioni che sono disponibili in questo sito web, a cui preferirei non dovere rispondere. Per favore, _leggete attentamente le informazioni qui fornite prima di contattarmi_. Ribadisco qui sotto alcuni punti.

1. Il programma d'esame per gli studenti non frequentanti è descritto in questo sito web.
2. Le modalità d'esame per gli studenti non frequentanti sono descritte in questo sito web.
3. I testi da utilizzare per la preparazione dell'esame per gli studenti non frequentanti sono descritti in questo sito web.
4. Per richiedere un incontro Google Meet con me, per favore, inviatemi un messaggio personale tramite Moodle. 

### Politica sulla disonestà accademica

Prendo sul serio l'integrità accademica e non mostrerò alcuna tolleranza per comportamenti disonesti. Evitate di commettere intenzionalmente o inavvertitamente uno qualsiasi di questi atti:

- dare, ricevere o utilizzare aiuti non autorizzati durante le prove in itinere o durante l'esame;
- copiare intenzionalmente o non intenzionalmente il linguaggio, la struttura o le idee di un'altra persona attribuendovene la paternità.

### Politica sulle disabilità

Se uno studente ha dei bisogni educativi speciali, lo incoraggio a farmelo sapere _privatamente_ il prima possibile. Rispetterò ovviamente il diritto alla privacy in materia, con tutto il cuore.


### Considerazioni finali

Come per tutti gli insegnamenti, ciò che gli studenti imparano dipende in larga misura dal loro impegno durante il semestre. Chiedere aiuto ai vostri compagni e a me è importante: non abbiate timore di fare una domanda su qualcosa che non avete capito o se volete verificare quello che pensate di avere capito.

**Questa pagina web è l'unica fonte che va consultata per informazioni sul programma dell'insegnamento e sulle modalità d'esame.**

