---
title: "Materiali didattici"
date: "Pagina aggiornata il `r Sys.Date()`"
---

## Dispensa

Tutto ciò che verrà discusso a lezione è presente nella dispensa [cvsm2023](https://ccaudek.github.io/cfa_book/).

La dispensa include tutte le istruzioni $\textsf{R}$ per lo svolgimento delle analisi guidate dei dati che sarà necessario conoscere per superare l'esame. 

## Libro di testo

Per chi volesse approfondire gli argomenti discussi a lezione, e per chi non frequenta le lezioni, consiglio il seguente testo:

- Brown, Timothy A. (2015). *Confirmatory factor analysis for applied research*. Guilford publications.

## Materiali supplementari

Il migliore testo introduttivo al linguaggio $\textsf{R}$ è 

- [R for Data Science](https://r4ds.had.co.nz/) 

Uno dei migliori testi che introducono e spiegano l'analisi di regressione può essere consultato gratuitamente utilizzando questo sito:

- [Regression and Other Stories](https://avehtari.github.io/ROS-Examples/index.html)

Una utile Shiny app per la visualizzazione dei modelli CFA (e SEM) definiti con la sintassi `lavaan` può essere trovata seguendo questo link:

- [shinySEM](https://utrecht-university.shinyapps.io/shinySEM/)

