---
title: "Laboratorio didattico"
date: "Pagina aggiornata il `r Sys.Date()`"
---

# Progetto

Il laboratorio didattico ha l'obiettivo di fornire agli studenti l'opportunità di applicare le conoscenze e gli strumenti acquisiti durante il corso in modo pratico e concreto. In particolare, gli studenti saranno impegnati nella produzione di un elaborato che riguarda la costruzione o la validazione di uno strumento psicometrico utilizzando dati reali raccolti durante il laboratorio stesso. Questo percorso include tutte le fasi necessarie, dal processo di costruzione fino alla validazione finale dello strumento.

## Modalità di svolgimento

Il laboratorio didattico prevede una serie di incontri sia collettivi, in classe, sia individuali per i vari gruppi, sotto la supervisione del docente. Inoltre, saranno organizzati incontri online attraverso il Forum di Moodle per consentire agli studenti di organizzarsi autonomamente.

## Consegne di lavoro

Prodotto atteso: file in formato RMarkdown. 

## Modalità di verifica

Presentazione orale del lavoro svolto e valutazione dell'elaborato scritto.

    


